WITH CTE AS(
SELECT 
	CT2_FILORI FILIAL,
	SUBSTRING(CT2_CLVLCR, 2, 6) CLIENTE_CR,
	SUBSTRING(CT2_KEY, CHARINDEX('00', CT2_KEY), 9) NF,
	SUM(CT2_VALOR) CREDITO
FROM CT2010
WHERE 
	CT2_DATA LIKE '2023%'
	AND CT2_CREDIT = '110201001'
	AND CT2_KEY <> ''
GROUP BY
	CT2_FILORI, 
	SUBSTRING(CT2_KEY, CHARINDEX('00', CT2_KEY), 9),
	SUBSTRING(CT2_CLVLCR, 2, 6) 
	)SELECT
		CTE.FILIAL,
		CTE.CLIENTE_CR,
		CTE.NF,
		CTE.CREDITO,
		SUM(CT.CT2_VALOR) DEBITO,
		ISNULL((
			SELECT
				SUM(SE.E1_VALOR) E1_VALOR
			FROM SE1010 SE
			WHERE 
				CTE.FILIAL = SE.E1_FILIAL
				AND CTE.NF = SE.E1_NUM
				AND CTE.CLIENTE_CR = SE.E1_CLIENTE
				AND SE.E1_EMISSAO LIKE '2023%'
		), 0) CONTA_RECEBER
	FROM CTE
		INNER JOIN CT2010 CT
			ON CT.CT2_FILORI = CTE.FILIAL
			AND SUBSTRING(CT.CT2_KEY, CHARINDEX('00',  CT.CT2_KEY),  9) = CTE.NF
			AND CT.CT2_DEBITO = '110201001'
			AND CT.CT2_DATA LIKE '2023%'
	GROUP BY
		CTE.FILIAL,
		CTE.NF,
		CTE.CREDITO,
		CTE.CLIENTE_CR
