-- Ultimo dia de compra de cada produto, e a diferencia em numero de mês até agora.

SELECT
	DISTINCT COD_PRODUTO,
	PRODUTO,
	EMISSAO, 
	DATEDIFF(mm, EMISSAO, GETDATE()) AS DATADIFF 
FROM VENDAS V1 WHERE EMISSAO = (SELECT MAX(EMISSAO) FROM VENDAS AS V2 WHERE V2.COD_PRODUTO = V1.COD_PRODUTO)
ORDER BY EMISSAO DESC;
