WITH CTE AS (
    SELECT
        ROW_NUMBER() OVER (PARTITION BY COD_PRODUTO, DEVOLUCAO ORDER BY (SELECT 0)) AS RowNumber
    FROM
       VENDAS WHERE NF = '000353734' AND COD_PRODUTO = '111748'
)
DELETE FROM CTE WHERE RowNumber > 1;
