SELECT NF, COD_PRODUTO 
	FROM VENDAS V 
	WHERE EXISTS 
		(
			SELECT NF, COD_PRODUTO FROM VENDAS VE 
				WHERE VE.NF = V.NF 
				AND COD_FIL = '020204' AND EMISSAO > '20221231'
				AND DUPLIC = 'S'
			GROUP BY NF,COD_PRODUTO
			HAVING COUNT(COD_PRODUTO) > 1
			)
