-- Pegar os preços de produtos de venda dentro da tabela DA1010 ( Esse Valor é o preço ao qual o produto deve ser vendido, ou seja valor minimo)
-- Join da tabel de venda para pegar o preço ao qual o produto foi vendido, quantidade e o vendedor que fez a venda

SELECT 
	DISTINCT D1.DA0_DESCRI,
	V.COD_FIL,
	D1.DA0_CODTAB,
	DA1_CODPRO,
	V.PRODUTO,
	V.GRPROD,
	V.GRUPOPROD,
	CASE SA.A1_PESSOA
		WHEN 'F' THEN 'FISICA'
		WHEN 'J' THEN 'JURIDICA'
		ELSE NULL 
	END AS RAZOA_SOCIAL,
	V.QUANTI AS QUANTIDADE,
	V.COD_VEND,
	V.VENDEDOR,
	V.COD_CLIENTE,
	DA1_PRCVEN AS PRECO_PREV_VENDA,
	(DA1_PRCVEN - (DA1_PRCVEN * 10 / 100)) AS VALOR_MINIMO_VENDA,
	V.PRCVEN AS PRECO_VENDA,
	V.QUANTI AS QUANTIDADE,
	V.EMISSAO AS DATA_VENDA
FROM DA0010 AS D1 
INNER JOIN DA1010 AS DA 
	ON D1.DA0_CODTAB = DA.DA1_CODTAB
INNER JOIN VENDAS AS V 
	ON DA.DA1_CODPRO = V.COD_PRODUTO
INNER JOIN SA1010 AS SA ON SA.A1_COD = V.COD_CLIENTE
	WHERE
	D1.DA0_DESCRI LIKE '%TABELA A_'
	ORDER BY V.EMISSAO DESC
