SELECT 
	SA.A1_CGC,
	CASE SA.A1_PESSOA
		WHEN 'J' THEN 'JURIDICA'
		WHEN 'F' THEN 'FISICA'
		ELSE 'NONE'
	END
	AS RAZAO_SOCIAL,
	SA.A1_COD + '-' +
	V.HISTORICO AS CLIENTE,
	V.COD_VEND + '-' +
	V.VENDEDOR AS VENDEDOR,
	SA.A1_ULTCOM,
	V.EMISSAO, V.QUANTI,
	V.PRCVEN, V.VENDA,
	V.FORNECEDOR,
	V.COD_PRODUTO, 
	V.PRODUTO,
	V.REGIAO,
	V.ESTADO
FROM  dbo.VENDAS AS V INNER JOIN
dbo.SA1010 AS SA ON SA.A1_COD = V.COD_CLIENTE AND V.EMISSAO = SA.A1_ULTCOM;
